
name: nombreindiferente
on:
  push:
    branches: main

jobs:
  despliege-firebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
         node-version: '14.x'
      - run: npm install
      - run: npm install -g @angular/cli
      - run: ng build
      - name: depliege final
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}



